import { createContext, useContext, useState, useEffect } from 'react';

export type LangCode = 'th' | 'en' | 'my' | 'lo' | 'zh' | 'km';

export const LANGUAGES: { code: LangCode; label: string; flag: string }[] = [
  { code: 'th', label: 'ไทย', flag: '🇹🇭' },
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'my', label: 'မြန်မာ', flag: '🇲🇲' },
  { code: 'lo', label: 'ລາວ', flag: '🇱🇦' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'km', label: 'ខ្មែរ', flag: '🇰🇭' },
];

export type Translations = typeof TH;

const TH = {
  // Navbar
  nav_dashboard: 'หน้าหลัก',
  nav_courses: 'คอร์สเรียน',
  nav_certificates: 'ใบประกาศ',
  nav_help: 'ช่วยเหลือ',
  nav_admin: 'Admin Panel',
  nav_logout: 'ออกจากระบบ',
  nav_platform_sub: 'ระบบ E-Learning สำหรับ รพ.สต. และ รพ.',
  nav_staff: 'เจ้าหน้าที่ รพ.สต.',
  nav_admin_role: 'ผู้ดูแลระบบ',

  // Auth - Login
  login_welcome: 'ยินดีต้อนรับกลับ 👋',
  login_subtitle: 'เข้าสู่ระบบเพื่อเริ่มเรียนต่อ',
  login_email: 'อีเมล',
  login_password: 'รหัสผ่าน',
  login_remember: 'จดจำอีเมลของฉัน',
  login_submit: 'เข้าสู่ระบบ',
  login_loading: 'กำลังเข้าสู่ระบบ...',
  login_no_account: 'ยังไม่มีบัญชี?',
  login_register_link: 'สมัครสมาชิกฟรี',
  login_error: 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
  login_tagline: 'ระบบ E-Learning\nสำหรับบุคลากร\nรพ.สต. และ รพ.',
  login_tagline_sub: 'โซลูชันซอฟต์แวร์สำหรับระบบสาธารณสุข\nโดย Bangkok Global Software Co., Ltd.',
  login_feat1: 'คอร์สเรียนสำหรับบุคลากร รพ.สต. และ รพ.',
  login_feat2: 'ใบประกาศรับรองผลการเรียน',
  login_feat3: 'ติดตามความก้าวหน้าการเรียน',

  // Auth - Register
  register_title: 'สร้างบัญชีใหม่ 🎉',
  register_subtitle: 'เริ่มต้นการเรียนรู้วันนี้',
  register_name: 'ชื่อ-นามสกุล',
  register_cid: 'เลขบัตรประชาชน (13 หลัก)',
  register_hospital: 'โรงพยาบาลสังกัด',
  register_position: 'ตำแหน่ง',
  register_submit: 'สมัครสมาชิก',
  register_loading: 'กำลังสมัคร...',
  register_has_account: 'มีบัญชีแล้ว?',
  register_login_link: 'เข้าสู่ระบบ',
  register_error_cid: 'เลขบัตรประชาชนต้องมี 13 หลัก',
  register_error_general: 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',

  // Dashboard
  dash_greeting: 'ยินดีต้อนรับกลับ 👋',
  dash_keep_learning: 'มาเรียนรู้ต่อกันเลย!',
  dash_progress: 'ความคืบหน้า',
  dash_total_courses: 'คอร์สทั้งหมด',
  dash_completed: 'เรียนจบแล้ว',
  dash_in_progress: 'กำลังเรียน',
  dash_view_all: '🎓 ดูคอร์สทั้งหมด',
  dash_your_courses: 'คอร์สของคุณ',
  dash_not_started: 'ยังไม่ได้เริ่มเรียน',
  dash_course_completed: 'เรียนจบแล้ว',
  dash_no_courses: 'ยังไม่มีคอร์ส',
  dash_hr: 'ชม.',
  dash_min: 'นาที',

  // Courses
  courses_title: '📚 คอร์สเรียนทั้งหมด',
  courses_search: 'ค้นหาคอร์ส...',
  courses_found: 'พบ',
  courses_unit: 'คอร์ส',
  courses_all: 'ทั้งหมด',
  courses_view: 'ดูรายละเอียด →',
  courses_completed_badge: 'จบแล้ว',
  courses_no_result: 'ไม่พบคอร์สที่ตรงกับการค้นหา',
  courses_error: 'ไม่สามารถโหลดคอร์สได้',
  courses_general_cat: 'ทั่วไป',

  // Certificates
  certs_title: '🏆 ใบประกาศของฉัน',
  certs_subtitle: 'ใบประกาศนียบัตรทั้งหมดที่ได้รับจากการเรียนจบคอร์ส',
  certs_total: 'ใบประกาศทั้งหมด',
  certs_empty_title: 'ยังไม่มีใบประกาศ',
  certs_empty_sub: 'เรียนจบคอร์สเพื่อรับใบประกาศนียบัตร',
  certs_go_courses: 'ไปดูคอร์ส',
  certs_issued: 'ออกเมื่อ',
  certs_download: '⬇️ ดาวน์โหลดใบประกาศ',
  certs_badge: 'สำเร็จการศึกษา',

  // Help page
  help_title: '💬 ศูนย์ช่วยเหลือและสนับสนุน',
  help_subtitle: 'เราพร้อมให้บริการและช่วยเหลือคุณตลอด 24 ชั่วโมง',
  help_faq_title: 'คำถามที่พบบ่อย (FAQ)',
  help_contact_title: 'ช่องทางติดต่อ',
  help_tips_title: '💡 เคล็ดลับการใช้งาน',
  help_tips_default: [
    'ใช้ Browser Chrome, Firefox, หรือ Safari เวอร์ชันล่าสุดเพื่อประสบการณ์ที่ดีที่สุด',
    'ดูวิดีโอด้วย Internet ความเร็วอย่างน้อย 5 Mbps เพื่อความลื่นไหล',
    'ระบบบันทึกความคืบหน้าอัตโนมัติ แต่อย่าลืมดูวิดีโอให้จบเพื่อให้นับเป็นเวลาเรียน',
    'คลิกที่ปุ่ม Dashboard เพื่อดูสถิติและความคืบหน้าของคุณ',
  ],
};

const EN: Translations = {
  nav_dashboard: 'Dashboard',
  nav_courses: 'Courses',
  nav_certificates: 'Certificates',
  nav_help: 'Help',
  nav_admin: 'Admin Panel',
  nav_logout: 'Logout',
  nav_platform_sub: 'Online Learning Platform',
  nav_staff: 'Health Staff',
  nav_admin_role: 'Administrator',

  login_welcome: 'Welcome Back 👋',
  login_subtitle: 'Sign in to continue learning',
  login_email: 'Email',
  login_password: 'Password',
  login_remember: 'Remember my email',
  login_submit: 'Sign In',
  login_loading: 'Signing in...',
  login_no_account: "Don't have an account?",
  login_register_link: 'Register for free',
  login_error: 'Invalid email or password',
  login_tagline: 'Learn New Skills\nFor Healthcare\nStaff Nationwide',
  login_tagline_sub: 'Develop community health capabilities\nwith high-quality online courses',
  login_feat1: 'Comprehensive courses for health staff',
  login_feat2: 'Certificate of completion',
  login_feat3: 'Track your learning progress',

  register_title: 'Create Account 🎉',
  register_subtitle: 'Start learning today',
  register_name: 'Full Name',
  register_cid: 'National ID (13 digits)',
  register_hospital: 'Hospital / Health Center',
  register_position: 'Position',
  register_submit: 'Register',
  register_loading: 'Registering...',
  register_has_account: 'Already have an account?',
  register_login_link: 'Sign In',
  register_error_cid: 'National ID must be 13 digits',
  register_error_general: 'An error occurred. Please try again.',

  dash_greeting: 'Welcome Back 👋',
  dash_keep_learning: "Let's continue learning!",
  dash_progress: 'Progress',
  dash_total_courses: 'Total Courses',
  dash_completed: 'Completed',
  dash_in_progress: 'In Progress',
  dash_view_all: '🎓 View All Courses',
  dash_your_courses: 'Your Courses',
  dash_not_started: 'Not started',
  dash_course_completed: 'Completed',
  dash_no_courses: 'No courses yet',
  dash_hr: 'hr',
  dash_min: 'min',

  courses_title: '📚 All Courses',
  courses_search: 'Search courses...',
  courses_found: 'Found',
  courses_unit: 'courses',
  courses_all: 'All',
  courses_view: 'View Details →',
  courses_completed_badge: 'Completed',
  courses_no_result: 'No courses match your search',
  courses_error: 'Failed to load courses',
  courses_general_cat: 'General',

  certs_title: '🏆 My Certificates',
  certs_subtitle: 'All certificates earned from completed courses',
  certs_total: 'Total Certificates',
  certs_empty_title: 'No certificates yet',
  certs_empty_sub: 'Complete a course to earn your certificate',
  certs_go_courses: 'Browse Courses',
  certs_issued: 'Issued on',
  certs_download: '⬇️ Download Certificate',
  certs_badge: 'Completed',

  help_title: '💬 Help & Support Center',
  help_subtitle: 'We are ready to assist you 24 hours a day',
  help_faq_title: 'Frequently Asked Questions (FAQ)',
  help_contact_title: 'Contact Channels',
  help_tips_title: '💡 Usage Tips',
  help_tips_default: [
    'Use the latest version of Chrome, Firefox, or Safari for the best experience',
    'Watch videos with at least 5 Mbps internet for smooth playback',
    'Progress is saved automatically, but complete videos to count as learning time',
    'Click the Dashboard button to view your statistics and progress',
  ],
};

const MY: Translations = {
  nav_dashboard: 'ပင်မစာမျက်နှာ',
  nav_courses: 'သင်တန်းများ',
  nav_certificates: 'လက်မှတ်များ',
  nav_help: 'အကူအညီ',
  nav_admin: 'Admin Panel',
  nav_logout: 'ထွက်မည်',
  nav_platform_sub: 'အွန်လိုင်းသင်ကြားမှုပလပ်ဖောင်း',
  nav_staff: 'ကျန်းမာရေးဝန်ထမ်း',
  nav_admin_role: 'စီမံခန့်ခွဲသူ',

  login_welcome: 'ပြန်လည်ကြိုဆိုပါသည် 👋',
  login_subtitle: 'သင်ယူမှုဆက်လက်ရန် ဝင်ရောက်ပါ',
  login_email: 'အီးမေးလ်',
  login_password: 'စကားဝှက်',
  login_remember: 'အီးမေးလ်မှတ်သားရန်',
  login_submit: 'ဝင်ရောက်မည်',
  login_loading: 'ဝင်ရောက်နေသည်...',
  login_no_account: 'အကောင့်မရှိသေးဘူးလား?',
  login_register_link: 'အခမဲ့မှတ်ပုံတင်မည်',
  login_error: 'အီးမေးလ် သို့မဟုတ် စကားဝှက်မှားသည်',
  login_tagline: 'ကျွမ်းကျင်မှုသစ်များသင်ယူပါ\nကျန်းမာရေးဝန်ထမ်းများအတွက်\nနိုင်ငံတစ်ဝှမ်း',
  login_tagline_sub:
    'အရည်အသွေးမြင့်အွန်လိုင်းသင်တန်းများဖြင့်\nကျောင်းသူများ၏ကျန်းမာရေးစွမ်းရည်ကိုမြှင့်တင်ပါ',
  login_feat1: 'ကျန်းမာရေးဝန်ထမ်းများအတွက်သင်တန်းများ',
  login_feat2: 'ပြီးမြောက်ကြောင်းလက်မှတ်',
  login_feat3: 'သင်ယူမှုတိုးတက်မှုကိုခြေရာခံပါ',

  register_title: 'အကောင့်အသစ်ဖန်တီးမည် 🎉',
  register_subtitle: 'ယနေ့ပဲသင်ယူမှုစတင်ပါ',
  register_name: 'နာမည်အပြည့်အစုံ',
  register_cid: 'နိုင်ငံသားကိုယ်ပိုင်နံပါတ် (၁၃ လုံး)',
  register_hospital: 'ဆေးရုံ / ကျန်းမာရေးစင်တာ',
  register_position: 'ရာထူး',
  register_submit: 'မှတ်ပုံတင်မည်',
  register_loading: 'မှတ်ပုံတင်နေသည်...',
  register_has_account: 'အကောင့်ရှိပြီးသားလား?',
  register_login_link: 'ဝင်ရောက်မည်',
  register_error_cid: 'နိုင်ငံသားကိုယ်ပိုင်နံပါတ် ၁၃ လုံးဖြစ်ရမည်',
  register_error_general: 'အမှားဖြစ်သည်။ ထပ်မံကြိုးစားပါ။',

  dash_greeting: 'ပြန်လည်ကြိုဆိုပါသည် 👋',
  dash_keep_learning: 'ဆက်လက်သင်ယူကြစို့!',
  dash_progress: 'တိုးတက်မှု',
  dash_total_courses: 'သင်တန်းအားလုံး',
  dash_completed: 'ပြီးမြောက်ပြီ',
  dash_in_progress: 'သင်ယူနေဆဲ',
  dash_view_all: '🎓 သင်တန်းအားလုံးကြည့်မည်',
  dash_your_courses: 'သင်၏သင်တန်းများ',
  dash_not_started: 'မစတင်သေးပါ',
  dash_course_completed: 'ပြီးမြောက်ပြီ',
  dash_no_courses: 'သင်တန်းမရှိသေးပါ',
  dash_hr: 'နာရီ',
  dash_min: 'မိနစ်',

  courses_title: '📚 သင်တန်းအားလုံး',
  courses_search: 'သင်တန်းရှာမည်...',
  courses_found: 'တွေ့ရှိသည်',
  courses_unit: 'သင်တန်း',
  courses_all: 'အားလုံး',
  courses_view: 'အသေးစိတ်ကြည့်မည် →',
  courses_completed_badge: 'ပြီးမြောက်ပြီ',
  courses_no_result: 'သင်တန်းမတွေ့ပါ',
  courses_error: 'သင်တန်းတင်မရပါ',
  courses_general_cat: 'ทั่วไป',

  certs_title: '🏆 ကျွန်ုပ်၏လက်မှတ်များ',
  certs_subtitle: 'ပြီးမြောက်သောသင်တန်းများမှရရှိသောလက်မှတ်များ',
  certs_total: 'လက်မှတ်အားလုံး',
  certs_empty_title: 'လက်မှတ်မရှိသေးပါ',
  certs_empty_sub: 'လက်မှတ်ရရန် သင်တန်းပြီးမြောက်ပါ',
  certs_go_courses: 'သင်တန်းကြည့်မည်',
  certs_issued: 'ထုတ်ပေးသောနေ့',
  certs_download: '⬇️ လက်မှတ်ဒေါင်းလုဒ်',
  certs_badge: 'ပြီးမြောက်ပြီ',

  help_title: '💬 အကူအညီနှင့်ပံ့ပိုးမှုစင်တာ',
  help_subtitle: 'ကျွန်ုပ်တို့သည် ၂၄ နာရီ သင့်ကိုကူညီရန်အသင့်ရှိသည်',
  help_faq_title: 'မကြာခဏမေးလေ့ရှိသောမေးခွန်းများ (FAQ)',
  help_contact_title: 'ဆက်သွယ်ရန်လမ်းကြောင်းများ',
  help_tips_title: '💡 အသုံးပြုရန်အကြံပြုချက်များ',
  help_tips_default: [
    'အကောင်းဆုံးအတွေ့အကြုံအတွက် Chrome, Firefox, Safari နောက်ဆုံးဗားရှင်းသုံးပါ',
    'ချောမွေ့သောဖွင့်ကြည့်မှုအတွက် အင်တာနက် 5 Mbps အနည်းဆုံးဖြင့်ကြည့်ပါ',
    'တိုးတက်မှုကိုအလိုအလျောက်သိမ်းဆည်းသည်၊ သင်ကြားချိန်ထည့်ရန်ဗီဒီယိုပြီးဆုံးပါ',
    'သင်၏စာရင်းဇယားနှင့်တိုးတက်မှုကြည့်ရန် Dashboard ကိုနှိပ်ပါ',
  ],
};

const LO: Translations = {
  nav_dashboard: 'ໜ້າຫຼັກ',
  nav_courses: 'ຫຼັກສູດ',
  nav_certificates: 'ໃບຢັ້ງຢືນ',
  nav_help: 'ຊ່ວຍເຫຼືອ',
  nav_admin: 'Admin Panel',
  nav_logout: 'ອອກຈາກລະບົບ',
  nav_platform_sub: 'ເວທີການຮຽນອອນລາຍ',
  nav_staff: 'ພະນັກງານສາທາລະນະສຸກ',
  nav_admin_role: 'ຜູ້ດູແລລະບົບ',

  login_welcome: 'ຍິນດີຕ້ອນຮັບກັບຄືນ 👋',
  login_subtitle: 'ເຂົ້າສູ່ລະບົບເພື່ອຮຽນຕໍ່',
  login_email: 'ອີເມລ',
  login_password: 'ລະຫັດຜ່ານ',
  login_remember: 'ຈື່ອີເມລຂອງຂ້ອຍ',
  login_submit: 'ເຂົ້າສູ່ລະບົບ',
  login_loading: 'ກຳລັງເຂົ້າສູ່ລະບົບ...',
  login_no_account: 'ຍັງບໍ່ມີບັນຊີ?',
  login_register_link: 'ລົງທະບຽນຟຣີ',
  login_error: 'ອີເມລ ຫຼື ລະຫັດຜ່ານບໍ່ຖືກຕ້ອງ',
  login_tagline: 'ຮຽນທັກສະໃໝ່\nສຳລັບພະນັກງານ\nສາທາລະນະສຸກທົ່ວປະເທດ',
  login_tagline_sub: 'ພັດທະນາຄວາມສາມາດດ້ານສາທາລະນະສຸກ\nດ້ວຍຫຼັກສູດອອນລາຍຄຸນນະພາບສູງ',
  login_feat1: 'ຫຼັກສູດຄົບຖ້ວນສຳລັບພະນັກງານສາທາລະນະສຸກ',
  login_feat2: 'ໃບຢັ້ງຢືນຜ່ານການຮຽນ',
  login_feat3: 'ຕິດຕາມຄວາມຄືບໜ້າການຮຽນ',

  register_title: 'ສ້າງບັນຊີໃໝ່ 🎉',
  register_subtitle: 'ເລີ່ມຕົ້ນການຮຽນຮູ້ມື້ນີ້',
  register_name: 'ຊື່-ນາມສະກຸນ',
  register_cid: 'ເລກບັດປະຊາຊົນ (13 ຕົວເລກ)',
  register_hospital: 'ໂຮງໝໍ / ສູນສາທາລະນະສຸກ',
  register_position: 'ຕຳແໜ່ງ',
  register_submit: 'ລົງທະບຽນ',
  register_loading: 'ກຳລັງລົງທະບຽນ...',
  register_has_account: 'ມີບັນຊີແລ້ວ?',
  register_login_link: 'ເຂົ້າສູ່ລະບົບ',
  register_error_cid: 'ເລກບັດປະຊາຊົນຕ້ອງມີ 13 ຕົວເລກ',
  register_error_general: 'ເກີດຂໍ້ຜິດພາດ ກະລຸນາລອງໃໝ່',

  dash_greeting: 'ຍິນດີຕ້ອນຮັບກັບຄືນ 👋',
  dash_keep_learning: 'ມາຮຽນຕໍ່ກັນເທາະ!',
  dash_progress: 'ຄວາມຄືບໜ້າ',
  dash_total_courses: 'ຫຼັກສູດທັງໝົດ',
  dash_completed: 'ຮຽນຈົບແລ້ວ',
  dash_in_progress: 'ກຳລັງຮຽນ',
  dash_view_all: '🎓 ເບິ່ງຫຼັກສູດທັງໝົດ',
  dash_your_courses: 'ຫຼັກສູດຂອງທ່ານ',
  dash_not_started: 'ຍັງບໍ່ໄດ້ເລີ່ມ',
  dash_course_completed: 'ຮຽນຈົບແລ້ວ',
  dash_no_courses: 'ຍັງບໍ່ມີຫຼັກສູດ',
  dash_hr: 'ຊ.ມ.',
  dash_min: 'ນາທີ',

  courses_title: '📚 ຫຼັກສູດທັງໝົດ',
  courses_search: 'ຄົ້ນຫາຫຼັກສູດ...',
  courses_found: 'ພົບ',
  courses_unit: 'ຫຼັກສູດ',
  courses_all: 'ທັງໝົດ',
  courses_view: 'ເບິ່ງລາຍລະອຽດ →',
  courses_completed_badge: 'ຈົບແລ້ວ',
  courses_no_result: 'ບໍ່ພົບຫຼັກສູດທີ່ຕ້ອງການ',
  courses_error: 'ບໍ່ສາມາດໂຫຼດຫຼັກສູດໄດ້',
  courses_general_cat: 'ທົ່ວໄປ',

  certs_title: '🏆 ໃບຢັ້ງຢືນຂອງຂ້ອຍ',
  certs_subtitle: 'ໃບຢັ້ງຢືນທັງໝົດທີ່ໄດ້ຮັບຈາກການຮຽນຈົບ',
  certs_total: 'ໃບຢັ້ງຢືນທັງໝົດ',
  certs_empty_title: 'ຍັງບໍ່ມີໃບຢັ້ງຢືນ',
  certs_empty_sub: 'ຮຽນຈົບຫຼັກສູດເພື່ອຮັບໃບຢັ້ງຢືນ',
  certs_go_courses: 'ໄປເບິ່ງຫຼັກສູດ',
  certs_issued: 'ອອກເມື່ອ',
  certs_download: '⬇️ ດາວໂຫຼດໃບຢັ້ງຢືນ',
  certs_badge: 'ສຳເລັດການສຶກສາ',

  help_title: '💬 ສູນຊ່ວຍເຫຼືອແລະສະໜັບສະໜຸນ',
  help_subtitle: 'ພວກເຮົາພ້ອມຊ່ວຍເຫຼືອທ່ານຕະຫຼອດ 24 ຊົ່ວໂມງ',
  help_faq_title: 'ຄຳຖາມທີ່ພົບເລື້ອຍໆ (FAQ)',
  help_contact_title: 'ຊ່ອງທາງຕິດຕໍ່',
  help_tips_title: '💡 ຄຳແນະນຳການໃຊ້ງານ',
  help_tips_default: [
    'ໃຊ້ Chrome, Firefox ຫຼື Safari ເວີຊັນລ່າສຸດ',
    'ດູວິດີໂອດ້ວຍ Internet ຢ່າງໜ້ອຍ 5 Mbps',
    'ລະບົບບັນທຶກຄວາມຄືບໜ້າອັດຕະໂນມັດ',
    'ຄລິກ Dashboard ເພື່ອເບິ່ງສະຖິຕິ',
  ],
};

const ZH: Translations = {
  nav_dashboard: '主页',
  nav_courses: '课程',
  nav_certificates: '证书',
  nav_help: '帮助',
  nav_admin: '管理面板',
  nav_logout: '退出登录',
  nav_platform_sub: '在线学习平台',
  nav_staff: '卫生工作人员',
  nav_admin_role: '管理员',

  login_welcome: '欢迎回来 👋',
  login_subtitle: '登录以继续学习',
  login_email: '电子邮件',
  login_password: '密码',
  login_remember: '记住我的邮件',
  login_submit: '登录',
  login_loading: '正在登录...',
  login_no_account: '还没有账号？',
  login_register_link: '免费注册',
  login_error: '邮箱或密码不正确',
  login_tagline: '学习新技能\n为全国\n卫生工作人员',
  login_tagline_sub: '通过高质量在线课程\n提升社区卫生能力',
  login_feat1: '适合卫生工作人员的完整课程',
  login_feat2: '课程完成证书',
  login_feat3: '追踪学习进度',

  register_title: '创建账户 🎉',
  register_subtitle: '今天开始学习',
  register_name: '全名',
  register_cid: '国家身份证号 (13位)',
  register_hospital: '医院 / 卫生中心',
  register_position: '职位',
  register_submit: '注册',
  register_loading: '注册中...',
  register_has_account: '已有账户？',
  register_login_link: '登录',
  register_error_cid: '身份证号必须是13位数字',
  register_error_general: '发生错误，请重试',

  dash_greeting: '欢迎回来 👋',
  dash_keep_learning: '继续学习吧！',
  dash_progress: '进度',
  dash_total_courses: '全部课程',
  dash_completed: '已完成',
  dash_in_progress: '进行中',
  dash_view_all: '🎓 查看全部课程',
  dash_your_courses: '我的课程',
  dash_not_started: '未开始',
  dash_course_completed: '已完成',
  dash_no_courses: '暂无课程',
  dash_hr: '小时',
  dash_min: '分钟',

  courses_title: '📚 全部课程',
  courses_search: '搜索课程...',
  courses_found: '找到',
  courses_unit: '个课程',
  courses_all: '全部',
  courses_view: '查看详情 →',
  courses_completed_badge: '已完成',
  courses_no_result: '未找到匹配课程',
  courses_error: '加载课程失败',
  courses_general_cat: '通用',

  certs_title: '🏆 我的证书',
  certs_subtitle: '从已完成课程中获得的所有证书',
  certs_total: '证书总数',
  certs_empty_title: '暂无证书',
  certs_empty_sub: '完成课程以获取证书',
  certs_go_courses: '浏览课程',
  certs_issued: '颁发于',
  certs_download: '⬇️ 下载证书',
  certs_badge: '已完成',

  help_title: '💬 帮助与支持中心',
  help_subtitle: '我们全天24小时为您提供帮助',
  help_faq_title: '常见问题 (FAQ)',
  help_contact_title: '联系方式',
  help_tips_title: '💡 使用技巧',
  help_tips_default: [
    '使用最新版 Chrome、Firefox 或 Safari 以获得最佳体验',
    '使用至少 5 Mbps 的网络流畅观看视频',
    '系统自动保存进度，但需看完视频才计入学习时间',
    '点击 Dashboard 查看您的统计和进度',
  ],
};

const KM: Translations = {
  nav_dashboard: 'ទំព័រដើម',
  nav_courses: 'វគ្គសិក្សា',
  nav_certificates: 'វិញ្ញាបនបត្រ',
  nav_help: 'ជំនួយ',
  nav_admin: 'Admin Panel',
  nav_logout: 'ចាកចេញ',
  nav_platform_sub: 'វេទិកាសិក្សាអនឡាញ',
  nav_staff: 'បុគ្គលិកសុខាភិបាល',
  nav_admin_role: 'អ្នកគ្រប់គ្រង',

  login_welcome: 'សូមស្វាគមន៍ 👋',
  login_subtitle: 'ចូលប្រព័ន្ធដើម្បីបន្តការសិក្សា',
  login_email: 'អ៊ីមែល',
  login_password: 'ពាក្យសម្ងាត់',
  login_remember: 'ចងចាំអ៊ីមែលរបស់ខ្ញុំ',
  login_submit: 'ចូលប្រព័ន្ធ',
  login_loading: 'កំពុងចូល...',
  login_no_account: 'មិនទាន់មានគណនី?',
  login_register_link: 'ចុះឈ្មោះដោយឥតគិតថ្លៃ',
  login_error: 'អ៊ីមែល ឬ ពាក្យសម្ងាត់មិនត្រឹមត្រូវ',
  login_tagline: 'រៀនជំនាញថ្មី\nសម្រាប់បុគ្គលិក\nសុខាភិបាលទូទាំងប្រទេស',
  login_tagline_sub: 'អភិវឌ្ឍសមត្ថភាពសុខាភិបាលសហគមន៍\nដោយមានវគ្គសិក្សាអនឡាញដ៏ល្អ',
  login_feat1: 'វគ្គសិក្សាពេញលេញសម្រាប់បុគ្គលិកសុខាភិបាល',
  login_feat2: 'វិញ្ញាបនបត្របញ្ចប់ការសិក្សា',
  login_feat3: 'តាមដានវឌ្ឍនភាពការសិក្សា',

  register_title: 'បង្កើតគណនីថ្មី 🎉',
  register_subtitle: 'ចាប់ផ្តើមរៀនថ្ងៃនេះ',
  register_name: 'ឈ្មោះពេញ',
  register_cid: 'លេខអត្តសញ្ញាណប័ណ្ណ (13 ខ្ទង់)',
  register_hospital: 'មន្ទីរពេទ្យ / មណ្ឌលសុខភាព',
  register_position: 'មុខតំណែង',
  register_submit: 'ចុះឈ្មោះ',
  register_loading: 'កំពុងចុះឈ្មោះ...',
  register_has_account: 'មានគណនីរួចហើយ?',
  register_login_link: 'ចូលប្រព័ន្ធ',
  register_error_cid: 'លេខអត្តសញ្ញាណប័ណ្ណត្រូវតែមាន 13 ខ្ទង់',
  register_error_general: 'មានបញ្ហា សូមព្យាយាមម្តងទៀត',

  dash_greeting: 'សូមស្វាគមន៍ 👋',
  dash_keep_learning: 'តោះបន្តរៀន!',
  dash_progress: 'វឌ្ឍនភាព',
  dash_total_courses: 'វគ្គសិក្សាទាំងអស់',
  dash_completed: 'បានបញ្ចប់',
  dash_in_progress: 'កំពុងរៀន',
  dash_view_all: '🎓 មើលវគ្គសិក្សាទាំងអស់',
  dash_your_courses: 'វគ្គសិក្សារបស់អ្នក',
  dash_not_started: 'មិនទាន់ចាប់ផ្តើម',
  dash_course_completed: 'បានបញ្ចប់',
  dash_no_courses: 'មិនទាន់មានវគ្គសិក្សា',
  dash_hr: 'ម.',
  dash_min: 'នាទី',

  courses_title: '📚 វគ្គសិក្សាទាំងអស់',
  courses_search: 'ស្វែងរកវគ្គសិក្សា...',
  courses_found: 'បានរក',
  courses_unit: 'វគ្គ',
  courses_all: 'ទាំងអស់',
  courses_view: 'មើលលម្អិត →',
  courses_completed_badge: 'បានបញ្ចប់',
  courses_no_result: 'រកមិនឃើញវគ្គសិក្សា',
  courses_error: 'មិនអាចផ្ទុកវគ្គសិក្សាបាន',
  courses_general_cat: 'ទូទៅ',

  certs_title: '🏆 វិញ្ញាបនបត្ររបស់ខ្ញុំ',
  certs_subtitle: 'វិញ្ញាបនបត្រទាំងអស់ដែលទទួលបានពីការបញ្ចប់វគ្គ',
  certs_total: 'វិញ្ញាបនបត្រទាំងអស់',
  certs_empty_title: 'មិនទាន់មានវិញ្ញាបនបត្រ',
  certs_empty_sub: 'បញ្ចប់វគ្គសិក្សាដើម្បីទទួលវិញ្ញាបនបត្រ',
  certs_go_courses: 'ទៅមើលវគ្គ',
  certs_issued: 'បានចេញនៅ',
  certs_download: '⬇️ ទាញយកវិញ្ញាបនបត្រ',
  certs_badge: 'បានបញ្ចប់',

  help_title: '💬 មជ្ឈមណ្ឌលជំនួយ',
  help_subtitle: 'យើងរួចខ្លួនជួយអ្នក 24 ម៉ោង',
  help_faq_title: 'សំណួរដែលសួរញឹកញាប់ (FAQ)',
  help_contact_title: 'មធ្យោបាយទំនាក់ទំនង',
  help_tips_title: '💡 គន្លឹះប្រើប្រាស់',
  help_tips_default: [
    'ប្រើ Chrome, Firefox ឬ Safari ជំនាន់ចុងក្រោយ',
    'មើលវីដេអូជាមួយ Internet យ៉ាងហោចណាស់ 5 Mbps',
    'ប្រព័ន្ធរក្សាទុកវឌ្ឍនភាពដោយស្វ័យប្រវត្តិ',
    'ចុច Dashboard ដើម្បីមើលស្ថិតិ',
  ],
};

const ALL_TRANSLATIONS: Record<LangCode, Translations> = {
  th: TH,
  en: EN,
  my: MY,
  lo: LO,
  zh: ZH,
  km: KM,
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'th',
  setLang: () => {},
  t: TH,
});

const STORAGE_KEY = 'bgs_lang';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    const saved = localStorage.getItem(STORAGE_KEY) as LangCode | null;
    return saved && ALL_TRANSLATIONS[saved] ? saved : 'th';
  });

  const setLang = (l: LangCode) => {
    setLangState(l);
    localStorage.setItem(STORAGE_KEY, l);
  };

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: ALL_TRANSLATIONS[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
